### PR TITLE
Add IIIF Curation Viewer

### PR DESCRIPTION
**Pull request by glenrobson**
Moving pull request #534 to this repo so the preview builds.

"On August 27, 2024, we released a new version of the “IIIF Curation Platform” (including the “IIIF Curation Viewer”) to support IIIF Presentation API 3.0. This pull request is to reflect the viewer’s compatibility status.
http://codh.rois.ac.jp/icp/prezi-3/"

### CODE REVIEW

**Comment by glenrobson** [comment]
Checklist:

- [ ] [🔗 0004 canvas-size](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0004-canvas-size/)
- [ ] [🔗 0005 image-service](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0005-image-service/)
- [ ] [🔗 0006 text-language](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0006-text-language/)
- [ ] [🔗 0007 string-formats](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0007-string-formats/)
- [ ] [🔗 0008 rights](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0008-rights/)
- [ ] [🔗 0009 book-1](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0009-book-1/)
- [ ] [🔗 0010 book-2-viewing-direction](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0010-book-2-viewing-direction/)
- [ ] [🔗 0029 metadata-anywhere](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0029-metadata-anywhere/)
- [ ] [🔗 0118 multivalue](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0118-multivalue/)
- [ ] [🔗 0283 missing-image](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0283-missing-image/)

**Comment by glenrobson** [comment]
@2SC1815J we had the following questions while reviewing the recipe support: 

regarding:
* [🔗 0006 text-language](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0006-text-language/)
* How do we select the French language so we can see the translations? 

Regarding:
 * [🔗 0007 string-formats](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0007-string-formats/)
 * How can you see the summary? Description shows the label
 * Attribution isn't correctly showing the HTML specifically the image tags.  
 
 Regarding:
*  [🔗 0008 rights](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0008-rights/)
* Same issue as above with the image not showing. We would mark this as partial support because it does support the rights information.

Regarding:
 * [🔗 0010 book-2-viewing-direction](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0010-book-2-viewing-direction/)
 * If you navigate by the << icons at the top when you press left you get a different image than when you click the left navigation on the image. 
 * Note partial support because this recipe also includes top to bottom navigation. 

Regarding:
 * [🔗 0029 metadata-anywhere](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0029-metadata-anywhere/)
 * We can't see the Canvas metadata which is required for this recipe.

**Comment by 2SC1815J** [comment]
@glenrobson Thank you very much for the review.
We would like to add some additional information below.

* [🔗 0006 text-language](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0006-text-language/)

Currently, the IIIF Curation Viewer only provides English and Japanese as UI languages.
Based on [recipe 0006](https://iiif.io/api/cookbook/recipe/0006-text-language/), I have created [a manifest](https://gist.github.com/2SC1815J/cad3d16ef083c0090dba994d7d4e2a4f) with English, French, and Japanese values.
You can see the display of English or Japanese values as follows.
[English values displayed in the IIIF Curation Viewer](http://codh.rois.ac.jp/software/iiif-curation-viewer/demo/?manifest=https://gist.githubusercontent.com/2SC1815J/cad3d16ef083c0090dba994d7d4e2a4f/raw/maniefst.json&lang=en)
[Japanese values displayed in the IIIF Curation Viewer](http://codh.rois.ac.jp/software/iiif-curation-viewer/demo/?manifest=https://gist.githubusercontent.com/2SC1815J/cad3d16ef083c0090dba994d7d4e2a4f/raw/maniefst.json&lang=ja)

* [🔗 0007 string-formats](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0007-string-formats/)

There was a bug in the handling of "summary." Now, "summary" is displayed from the description menu item.
Referring to [the specification](https://iiif.io/api/presentation/3.0/#45-html-markup-in-property-values) ("Clients should allow only a, b, br, i, img, p, small, span, sub and sup tags. Clients may choose to remove any and all tags"), the IIIF Curation Viewer only allows a, b, br, i, p, and span tags as HTML markup, and does not allow img tags.

* [🔗 0008 rights](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0008-rights/)

Same as above, the img tag is not allowed in the IIIF Curation Viewer.

* [🔗 0010 book-2-viewing-direction](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0010-book-2-viewing-direction/)

The "«" button on the toolbar always moves in the "prev" direction, regardless of the "viewingDirection" setting.
On the other hand, the "<" button on the left edge of the image will move you to turn the page in that direction. That is, if the "viewingDirection" setting is "left-to-right," it moves in the "prev" direction, and if it is "right-to-left," it moves in the "next" direction.
It is the intended behavior.

* [🔗 0029 metadata-anywhere](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0029-metadata-anywhere/)

To view the Canvas information, click the third button (link icon) from the right on the toolbar.

**Comment by glenrobson** [comment]
Regarding:

 * [🔗 0006 text-language](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0006-text-language/)
I'm afraid we can't add the Curation Viewer to this recipe unless it supports accessing and displaying all language labels and values as this is the main focus of the recipe. For information you don't need to translate the interface language of the curation viewer to support French but there has to be a way for the user to select and see the French metadata for this recipe to be supported. 

* [🔗 0007 string-formats](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0007-string-formats/)
* [🔗 0008 rights](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0008-rights/)

We appreciate your point and are happy to approve this supports the recipe. A potential UX improvement is to strip the image tag completely but this doesn't affect the recipe support. (Thanks for fixing the Summary)

* [🔗 0010 book-2-viewing-direction](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0010-book-2-viewing-direction/)

Thank you for clarifying. We accept this recipe is partially supported (due to the top-bottom not being supported) .

We had another question, should the thumbnails in the thumbnail preview be reveresed? 

*  [🔗 0029 metadata-anywhere](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0029-metadata-anywhere/)

Thank you. We agree this is supported.

**Comment by 2SC1815J** [comment]
@glenrobson Thank you for the re-review.

* [🔗 0006 text-language](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0006-text-language/)

The IIIF Curation Viewer now supports displaying any language labels and values via the GET parameter "lang."
Interface language is provided in English when the GET parameter "lang" value is other than "ja."
[English labels and values displayed in the IIIF Curation Viewer](http://codh.rois.ac.jp/software/iiif-curation-viewer/demo/?manifest=https://iiif.io/api/cookbook/recipe/0006-text-language/manifest.json&lang=en)
[French labels and values displayed in the IIIF Curation Viewer](http://codh.rois.ac.jp/software/iiif-curation-viewer/demo/?manifest=https://iiif.io/api/cookbook/recipe/0006-text-language/manifest.json&lang=fr)

By the way, if the IIIF manifest contains Japanese labels and values, the Universal Viewer does not seem to be able to display those labels and values (Japanese cannot be selected from Setting, and adding "&local=ja-JP" to the viewer's URI does not work).
[Display of the manifest containing Japanese labels and values in the UV](https://uv-v3.netlify.app/#?manifest=https%3A%2F%2Fgist.githubusercontent.com%2F2SC1815J%2Fcad3d16ef083c0090dba994d7d4e2a4f%2Fraw%2Fmaniefst.json)

The UV is listed as supporting recipe 0006. Does "supporting recipe  0006" mean that displaying all language labels and values listed in any given manifest is not required, but is it sufficient to display all language labels and values listed in the manifest of recipe 0006?

* [🔗 0007 string-formats](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0007-string-formats/)
* [🔗 0008 rights](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0008-rights/)

Thanks for the suggestion. We will consider it in a future version.

* [🔗 0010 book-2-viewing-direction](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0010-book-2-viewing-direction/)

We understand and agree that IIIF Curation Viewer will be listed as "partially supported" in this recipe. 

When we first released the IIIF Curation Viewer in 2014, many IIIF manifests published by institutions in Japan did not include a "viewingDirection" description, even though they were right-to-left documents. Since the IIIF Curation Viewer is mainly used in Japan, the viewer behavior without the "viewingDirection" description is to move from right to left. Thus, the manifest of [0009 book-1](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0009-book-1/) without a "viewingDirection" will be displayed as a right-to-left document in the IIIF Curation Viewer. Though this viewer behavior differs from the IIIF Presentation API specification, which defines left-to-right as the default, please understand it is because this viewer is mainly used in East Asian cultures.

In the ten years of providing the IIIF Curation Viewer in Japan, I do not recall any particular problems with the order of the thumbnails. Even in Japan, most document computer interfaces are displayed from left to right. So, it is not a strange feeling if thumbnails of right-to-left documents are displayed in left-to-right order (each row of thumbnails in top-to-bottom order) on a separate screen from the main image as in the IIIF Curation Viewer.

It would be confusing if clicking on the left or right edge of the main image does not move the page in that direction or if the thumbnails are shown in a single line from left to right just below the main image for right-to-left documents. Also, suppose thumbnails are displayed on a separate screen from the main image in right-to-left order (each row of thumbnails in top-to-bottom order). In that case, I think such displays would confuse because they are unfamiliar.

* [🔗 0029 metadata-anywhere](https://preview.iiif.io/cookbook/feature/curation-viewer/recipe/0029-metadata-anywhere/)

Thank you for the confirmation.

**Comment by glenrobson** [comment]
@2SC1815J thank you for your comments above. I have made some changes to the multilingul recipe in the following pull request:

https://github.com/IIIF/cookbook-recipes/pull/541/files

Are you OK with those changes? If so I think we can merge that pull request into this one and then merge this one into the main.

Thanks for submitting the Curation viewer, we look forward to adding it to the cookbook.

**Comment by 2SC1815J** [comment]
@glenrobson Thank you for making the appropriate changes.
We agree to the proposed changes and are delighted that the IIIF Curation Viewer will be added to the cookbook.
Thank you very much again.

**Pull request merged**
