### PR TITLE
Add Glycerine Viewer

### PR DESCRIPTION
**Pull request by glenrobson**
From original [pull request](https://github.com/IIIF/cookbook-recipes/pull/490):

"Initially designed for the sophisticated annotation features of [Glycerine Workbench](https://glycerine.io/), [Glycerine Viewer](https://github.com/Systemik-Solutions/glycerine-viewer) has been released as an open source IIIF viewer to support IIIF manifests and compliant annotations built with other tools. Developed with a contemporary Vue 3 framework, Glycerine Viewer has an elegant interface, supports the IIIF Presentation API and provides the most comprehensive annotation feature set of any IIIF Viewer."

### CODE REVIEW

**Comment by glenrobson** [comment]
Recipes supported:

 1. Simplest Manifest - Single Image File - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0001-mvm-image/)
 2. Support Deep Viewing with Basic Use of a IIIF Image Service - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0005-image-service/)
 3. Internationalization and Multi-language Values - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0006-text-language/)
 4. Embedding HTML in descriptive properties - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0007-string-formats/)
 5. Rights statement - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0008-rights/)
 6. Simple Manifest - Book - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0009-book-1/)
 7. HTML in Annotations - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0019-html-in-annotations/)
 8. Simple Annotation — Tagging - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0021-tagging/)
 9. Metadata on any Resource - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0029-metadata-anywhere/)
 10. Simple Collection - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0032-collection/)
 11. Providing Alternative Representations - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0046-rendering/)
 12. Linking to Web Page of an Object - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0047-homepage/)
 13. Linking to Structured Metadata - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0053-seeAlso/)
 14. Image Thumbnail for Manifest - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0117-add-image-thumbnail/)
 15. Displaying Multiple Values with Language Maps - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0118-multivalue/)
 16. Annotating a specific point of an image - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0135-annotating-point-in-canvas/)
 17. Load Manifest Beginning with a Specific Canvas - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0202-start-canvas/)
 18. Acknowledge Content Contributors - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0234-provider/)
 19. Tagging with an External Resource - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0258-tagging-external-resource/)
 20. Annotation with a Non-Rectangular Polygon (Updated) - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0261-non-rectangular-commenting/)
 21. Simplest Annotation - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0266-full-canvas-annotation/)
 22. Embedded or referenced Annotations - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0269-embedded-or-referenced-annotations/)
 23. Missing Images in a Sequence - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0283-missing-image/)
 24. Addressing a Spatial Region - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0299-region/)
 25. Linking external Annotations targeting a Canvas to a Manifest - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0306-linking-annotations-to-manifests/)
 26. Image in Annotations - [preview](https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0377-image-in-annotation/)

**Comment by triplingual** [comment]
Validated:
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅
1. ✅

**Comment by glenrobson** [comment]
Comments: 

PointSelector seems slow (could be the image server). 

0258-tagging-external-resource/ - a bit difficult to find, need to click the tag. Will need to remove the: No viewers currently implement this tagging approach

0261-non-rectangular-commenting - remove (Updated)

**Comment by glenrobson** [comment]
Need to fix Newspaper attribute manifest so that it has a opening and closing html tag in attribution.

**Comment by glenrobson** [comment]
Potentially add Newspaper example:

https://demo.viewer.glycerine.io/viewer?iiif-content=https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0068-newspaper/newspaper_title-collection.json

Add support for MultiVolume work: https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0030-multi-volume/

**Comment by yangli0516** [comment]
Thanks for the feedbacks @glenrobson . To reply your comments:

> PointSelector seems slow (could be the image server).

It is probably due to the size of image in recipe 0135.

> 0258-tagging-external-resource/ - a bit difficult to find, need to click the tag. Will need to remove the: No viewers currently implement this tagging approach

The "Tag Details" link is designed this way to align with other tag information such as tag description and hierarchy generated from the Glycerine Workbench. We will consider adding tooltips in the UI or emphasizing this in the documentation.

> 0261-non-rectangular-commenting - remove (Updated)

I saw you already did this fix in the master branch.

**Comment by yangli0516** [comment]
> Potentially add Newspaper example:
> 
> https://demo.viewer.glycerine.io/viewer?iiif-content=https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0068-newspaper/newspaper_title-collection.json
> 
> Add support for MultiVolume work: https://preview.iiif.io/cookbook/glycerine-viewer/recipe/0030-multi-volume/

I have added Glycerine Viewer into those two recipes in the pull request #496

**Pull request merged**
