### PR TITLE
Recipe #0008 — Rights

### PR DESCRIPTION
**Pull request by triplingual**
This PR addresses Issue 8, creating recipe #8, inclusion of rights statements, licenses, or other required statements. It won't pass the validator because the validator limits Creative Commons licenses to 4.0 versions, and the license for the media in this recipe uses 3.0.

I'm totally open to using other media, though.

Apologies for the lengthy red herring commit history. I erroneously merged the code for recipe #7 into this branch and then backed out the differences. 😩 Start at 1785ae3 for the actual work on this recipe.

### CODE REVIEW

**Comment by glenrobson** [comment]
(Automated comment): Branch aviliable for testing at https://preview.iiif.io/cookbook/0008-rights

**Comment by triplingual** [comment]
Added link to public UV implementation per conversation on cookbook call of 9 April 2020. (& as long as I was committing that, I added the link to the CC icon.)

**Comment by glenrobson** [comment]
Hi Trip,

The cookbook editors reviewed your recipe and asked if you could implement the new viewer and viewJson imports then this is also good to go to the TRC.

Thanks

**Comment by glenrobson** [comment]
(Automated comment): Branch available for testing at https://preview.iiif.io/cookbook/0008-rights

**Comment by triplingual** [comment]
@glenrobson Thanks for the notice!

Possibly foolish Q: Presumably I should list only the viewers in which the manifest is currently working, or should I retain all that are in the include with the assumption we'll shake out the non-working ones later?

**Comment by glenrobson** [comment]
Hi Trip, yes just add the ones that work and remove the ones that don't.

**Comment by glenrobson** [comment]
Can we merge in Jon's comma pull request: https://github.com/IIIF/cookbook-recipes/pull/191

**Pull request merged**
