### PR TITLE
Added Theseus Viewer support

### PR DESCRIPTION
**Pull request by glenrobson**
https://theseusviewer.org/

Bringing #501 into main repo so we get the preview.

### CODE REVIEW

**Comment by glenrobson** [comment]
- [x] [🔗 0001 mvm-image](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0001-mvm-image/)
- [x] [🔗 0002 mvm-audio](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0002-mvm-audio/)
- [x] [🔗 0003 mvm-video](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0003-mvm-video/)
- [x] [🔗 0004 canvas-size](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0004-canvas-size/)
- [x] [🔗 0005 image-service](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0005-image-service/)
- [x] [🔗 0006 text-language](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0006-text-language/)
- [x] [🔗 0007 string-formats](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0007-string-formats/)
- [x] [🔗 0008 rights](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0008-rights/)
- [x] [🔗 0009 book-1](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0009-book-1/)
- [x] [🔗 0010 book-2-viewing-direction](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0010-book-2-viewing-direction/)
- [x] [🔗 0011 book-3-behavior](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0011-book-3-behavior/)
- [x] [🔗 0013 placeholderCanvas](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0013-placeholderCanvas/)
- [x] [🔗 0014 accompanyingcanvas](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0014-accompanyingcanvas/)
- [x] [🔗 0015 start](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0015-start/)
- [x] [🔗 0017 transcription-av](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0017-transcription-av/)
- [x] [🔗 0019 html-in-annotations](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0019-html-in-annotations/)
- [x] [🔗 0021 tagging](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0021-tagging/)
- [ ] [🔗 ~~0022 linking-with-a-hotspot~~](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0022-linking-with-a-hotspot/) - not supported
- [x] [🔗 0024 book-4-toc](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0024-book-4-toc/)
- [x] [🔗 0026 toc-opera](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0026-toc-opera/)
- [x] [🔗 0029 metadata-anywhere](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0029-metadata-anywhere/)
- [x] [🔗 0030 multi-volume](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0030-multi-volume/)
- [x] [🔗 0031 bound-multivolume](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0031-bound-multivolume/)
- [x] [🔗 0032 collection](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0032-collection/)
- [x] [🔗 0033 choice](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0033-choice/)
- [x] [🔗 0035 foldouts](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0035-foldouts/)
- [x] [🔗 0036 composition-from-multiple-images](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0036-composition-from-multiple-images/)
- [x] [🔗 0040 image-rotation-service](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0040-image-rotation-service/)
- [x] [🔗 0046 rendering](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0046-rendering/)
- [x] [🔗 0047 homepage](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0047-homepage/)
- [ ] [🔗 0053 Linking to Structured Metadata](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0053-seeAlso/)
- [ ] [🔗 0065 Table of Contents for Multiple A/V Files on Multiple Canvases](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0065-opera-multiple-canvases/)
- [ ] [🔗 0117 Image Thumbnail for Manifest](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0117-add-image-thumbnail/)
- [ ] [🔗 0118 Displaying Multiple Values with Language Maps](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0118-multivalue/)
- [ ] [🔗 0135 Annotating a specific point of an image](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0135-annotating-point-in-canvas/)
- [ ] [🔗 0139 Represent Canvas Fragment as a Geographic Area in a Web Mapping Client](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0139-geolocate-canvas-fragment/)
- [ ] [🔗 0202 Load Manifest Beginning with a Specific Canvas](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0202-start-canvas/)
- [ ] [🔗 0219 Using Caption and Subtitle Files with Video Content](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0219-using-caption-file/)
- [ ] [🔗 0230 Navigation by Chronology](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0230-navdate/navdate-collection.json&collection=https://theseus-viewer.netlify.app/cookbook-collection.json)
- [ ] [🔗 0234 Acknowledge Content Contributors](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0234-provider/)
- [ ] [🔗 0258 Tagging with an External Resource](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0258-tagging-external-resource/)
- [ ] [🔗 0261 Annotation with a Non-Rectangular Polygon](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0261-non-rectangular-commenting/)
- [ ] [🔗 0266 Simplest Annotation](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0266-full-canvas-annotation/)
- [ ] [🔗 0269 Embedded or referenced Annotations](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0269-embedded-or-referenced-annotations/)
- [ ] [🔗 0283 Missing Images in a Sequence](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0283-missing-image/)
- [ ] [🔗 0299 Addressing a Spatial Region](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0299-region/)
- [ ] [🔗 0306 Linking external Annotations targeting a Canvas to a Manifest](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0306-linking-annotations-to-manifests/)
- [ ] [🔗 0377 Image in Annotations](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0377-image-in-annotation/)
- [ ] [🔗 0434 Multiple Choice of Audio Formats in a Single View (Canvas)](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0434-choice-av/)

**Comment by glenrobson** [comment]
Test in aviary: https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0065-opera-multiple-canvases/

**Comment by glenrobson** [comment]
We may need to remove the Label from the annotation as its confusing and doesn't add anything:

https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0135-annotating-point-in-canvas/

Currently viewer shows the label rather than the textual body but will show body once label has been removed.

**Comment by glenrobson** [comment]
Look at this recipe:

https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0139-geolocate-canvas-fragment/

maybe remove the annotation label but go over the text. 

Viewer should show the property/@label

**Comment by glenrobson** [comment]
Remove from first example:

https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0306-linking-annotations-to-manifests/

**Comment by glenrobson** [comment]
Add Newspaper

**Comment by stephenwf** [comment]
Propose to add - 0154 Locate a Manifest on a Web Map
https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0154-geo-extension/

https://theseus-viewer.netlify.app/?iiif-content=https://iiif.io/api/cookbook/recipe/0154-geo-extension/manifest.json&collection=https://theseus-viewer.netlify.app/cookbook-collection.json&panel=informationPanel

**Comment by stephenwf** [comment]
Propose to add - 0240 Locate multiple canvases on a Web Map
https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0240-navPlace-on-canvases/

https://theseus-viewer.netlify.app/?iiif-content=https://iiif.io/api/cookbook/recipe/0240-navPlace-on-canvases/manifest.json&panel=navPlace

**Comment by stephenwf** [comment]
Propose to add 0074 Using Caption and Subtitle Files in Multiple Languages with Video Content
https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0074-multiple-language-captions/

https://theseusviewer.org/?iiif-content=https%3A%2F%2Fiiif.io%2Fapi%2Fcookbook%2Frecipe%2F0074-multiple-language-captions%2Fmanifest.json

**Comment by stephenwf** [comment]
Propose to add 0022 Linking with a hotspot
https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0022-linking-with-a-hotspot/

https://theseusviewer.org/?iiif-content=https%3A%2F%2Fpreview.iiif.io%2Fcookbook%2Ffeature%2Ftheseus-viewer%2Frecipe%2F0022-linking-with-a-hotspot%2Fmanifest.json&panel=annotations

**Comment by glenrobson** [comment]
Work to do to get this merged (to be confirmed in cookbook meeting):

Cookbook group review:
- [ ] [0154 Locate a Manifest on a Web Map](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0154-geo-extension/)
- [ ] [0240 Locate multiple canvases on a Web Map](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0240-navPlace-on-canvases/)
- [ ] [0074 Using Caption and Subtitle Files in Multiple Languages with Video Content](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0074-multiple-language-captions/)
- [ ] [0022 Linking with a hotspot](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0022-linking-with-a-hotspot/)
- [ ] OK to approve [🔗 0135 Annotating a specific point of an image](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0135-annotating-point-in-canvas/) and [🔗 0139 Represent Canvas Fragment as a Geographic Area in a Web Mapping Client](https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0139-geolocate-canvas-fragment/) as they do the same as other viewers and label issue tackled in #518? 

Stephen:
- [ ] Remove thesus from the first example: https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0306-linking-annotations-to-manifests/

**Comment by robcast** [comment]
just a note to remind me to tell stephen about UX inconsistency with 0154 (map in about pane) vs 0240 (map icon in left toolbar)...

**Comment by triplingual** [comment]
For Recipe 74 (#270), a person can change the caption language by changing the primary interface language in the "About this item" interface.  However, the change only works for going from Italiano to English, not the reverse. Changing from Italiano to English also turns the CC off.

Steps to reproduce:
1. Load [the recipe](https://theseusviewer.org/?iiif-content=https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0074-multiple-language-captions/manifest.json) in Theseus
1. Press play
1. Turn on the closed captions (defaults to English)
1. Action the "About this item" link
1. Choose Italiano from the "Select an item" dropdown
1. Captions should stay on, and remain in English
1. From the gear icon in the AV player, select Captions and then "Sottotitoli in formato WebVTT"
1. Verify that the captions are in Italiano
1. Action the "About this item" link if necessary
1. Choose English from the "Select an item" dropdown
1. Captions should get turned off
1. Turn on captions
1. Captions should be in English

The behavior is slightly different when changing the order of the language selected:
1. Load [the recipe](https://theseusviewer.org/?iiif-content=https://preview.iiif.io/cookbook/feature/theseus-viewer/recipe/0074-multiple-language-captions/manifest.json) in Theseus
1. Press play
1. Turn on the closed captions (defaults to English)
1. From the gear icon in the AV player, select Captions and then "Sottotitoli in formato WebVTT"
1. Verify that the captions are in Italiano
1. Action the "About this item" link
1. Choose English from the "Select an item" dropdown
1. Captions should stay on, and remain in Italian
7. From the gear icon in the AV player, select Captions and then "Captions in WebVTT format"
1. Verify that the captions are in English
1. Action the "About this item" link if necessary
1. Choose Italiano from the "Select an item" dropdown
1. Captions should get turned off
1. Turn on captions
1. Captions should be in English

There's probably a bigger matrix to make to consider other/all possible paths, but perhaps these will suffice for now.

**Comment by stephenwf** [comment]
@robcast 
>just a note to remind me to tell stephen about UX inconsistency with 0154 (map in about pane) vs 0240 (map icon in left toolbar)...

Yes! The Manifest map is quite underwhelming, not much room to explore, especially if its a full GeoJSON geometry. Have thought about trying to make it so that you can "expand" and view it on the main area, but not found a nice way to do that. (I'm imagining that there might be cases where both the Manifest and Canvases have GeoJSON attached). 

@triplingual 
The captions and handling the changing of language is tricky. I was able to reliably change the captions but it would pause the video. I think I need to maybe look into how to handle this more smoothly. 

The main things I was aiming for: 
- You can change the captions from the player using the cog icon
- You should see the captions that match your browser language by default

But there is definitely work to do on the switching. Happy to go and make some improvements on that and mark this as partial support for now?

**Comment by glenrobson** [comment]
I'm going to merge this in preperation for Trips recipe.

**Pull request merged**
