### PR TITLE
Recipe #0010 — Book (viewingDirection variations)

### PR DESCRIPTION
**Pull request by triplingual**
This PR addresses Issue #10, creating recipe 10, variations in use of the `viewingDirection` property.

### CODE REVIEW

**Comment by glenrobson** [comment]
(Automated comment): Branch available for testing at https://preview.iiif.io/cookbook/0010-book-2-viewing-direction

**Comment by triplingual** [comment]
Results of Cookbook working group call 15 May:
- [ ] Line highlighting for TTB
- [ ] Swap out for new content
- [ ] Add service block

**Comment by glenrobson** [comment]
Todo:

- [ ] Remove boilerplate text: "Provide a bulleted list..."
- [ ] Change title to something like "Viewing direction and its effect on navigation"
- [ ] First sentence in the Use Case section should introduce the use case (for this recipe, being rtl reading) with a sensible example

**Comment by glenrobson** [comment]
Just checking where this recipe is. There is one open item on:

https://github.com/IIIF/trc/issues/40

"First sentence in the Use Case section should introduce the use case (for this recipe, being rtl reading) with a sensible example"

**Comment by triplingual** [comment]
😮 Totally forgot this change. Will re-uptake and finish it out.

**Comment by triplingual** [comment]
Maybe I didn't forget it after all. Do you think https://github.com/IIIF/cookbook-recipes/pull/148/commits/7c2a3934def3f5e2d5cb38717abcedaa43b734b9 addresses it?

**Comment by kirschbombe** [comment]
I think it addresses the feedback, @triplingual

**Comment by glenrobson** [comment]
Looks good to me too.

**Comment by glenrobson** [comment]
Changes made after TRC review and cookbook group did a review.

**Pull request merged**
