### PR TITLE
Adding license information for 30min clock

### PR DESCRIPTION
**Pull request by glenrobson**
It has been flagged that we should be referencing the license and author of the 30min video in the IIIF fixtures repository. This pull request adds this attribution and I will update the fixtures repo to say this is required. 

I don't think this needs TRC approval but I will flag it as a change to the TRC.

### CODE REVIEW

**Comment by glenrobson** [comment]
Added license and attribution to:

https://preview.iiif.io/cookbook/30_min_clock_attribution/recipe/0003-mvm-video/

and

https://preview.iiif.io/cookbook/30_min_clock_attribution/recipe/0015-start/

**Review by kirschbombe — APPROVED** [review]
Thanks, Glen!

**Comment by glenrobson** [comment]
TODO:
 * Change first video to: https://fixtures.iiif.io/info.html?file=/video/indiana/lunchroom_manners/high/lunchroom_manners_1024kb.mp4
 * Add attribution to start recipe manifest.

**Comment by glenrobson** [comment]
Changes made.

**Pull request merged**
