### PR TITLE
Trying another form of annotation

### PR DESCRIPTION
**Pull request by glenrobson**

### CODE REVIEW

**Comment by glenrobson** [comment]
@triplingual just checking if this passes validation. I think it will and if it does if you agree feel free to merge to your branch if you are OK with it.

**Comment by triplingual** [comment]
Right, so this matches up with what you mentioned on Slack, as far as I can tell. And the validator doesn't like it.
```
Message: Error 5 of 6.
 Message: {'id': '/recipe/0040-image-rotation-service/annotation/b1/1', 'type': 'SpecificResource', 'source': {'id': 'https://iiif.io/api/image/3.0/example/reference/85a96c630f077e6ac6cb984f1b752bbf-0-21198-zz00022840-1-master/full/max/0/default.jpg', 'type': 'Image', 'format': 'image/jpeg', 'width': 3375, 'height': 2250, 'service': [{'id': 'https://iiif.io/api/image/3.0/example/reference/85a96c630f077e6ac6cb984f1b752bbf-0-21198-zz00022840-1-master', 'type': 'ImageService3', 'profile': 'level1'}]}, 'selector': {'@context': 'http://iiif.io/api/annex/openannotation/context.json', 'type': 'iiif:ImageApiSelector', 'rotation': '90'}} is not valid under any of the given schemas
 **
 Json_path: $.items[0].items[0].items[0].body
 Instance: {'id': '/recipe/0040-image-rotation-service/annotation/b1/1', 'type': 'SpecificResource', 'source': '{ ... }', 'selector': '{ ... }'}
 Context: [<ValidationError: "{'id': '/recipe/0040-image-rotation-service/annotation/b1/1', 'type': 'SpecificResource', 'source': {'id': 'https://iiif.io/api/image/3.0/example/reference/85a96c630f077e6ac6cb984f1b752bbf-0-21198-zz00022840-1-master/full/max/0/default.jpg', 'type': 'Image', 'format': 'image/jpeg', 'width': 3375, 'height': 2250, 'service': [{'id': 'https://iiif.io/api/image/3.0/example/reference/85a96c630f077e6ac6cb984f1b752bbf-0-21198-zz00022840-1-master', 'type': 'ImageService3', 'profile': 'level1'}]}, 'selector': {'@context': 'http://iiif.io/api/annex/openannotation/context.json', 'type': 'iiif:ImageApiSelector', 'rotation': '90'}} is not valid under any of the given schemas">, <ValidationError: "'Choice' was expected">, <ValidationError: "'items' is a required property">, <ValidationError: "'items' is a required property">, <ValidationError: "{'id': '/recipe/0040-image-rotation-service/annotation/b1/1', 'type': 'SpecificResource', 'source': {'id': 'https://iiif.io/api/image/3.0/example/reference/85a96c630f077e6ac6cb984f1b752bbf-0-21198-zz00022840-1-master/full/max/0/default.jpg', 'type': 'Image', 'format': 'image/jpeg', 'width': 3375, 'height': 2250, 'service': [{'id': 'https://iiif.io/api/image/3.0/example/reference/85a96c630f077e6ac6cb984f1b752bbf-0-21198-zz00022840-1-master', 'type': 'ImageService3', 'profile': 'level1'}]}, 'selector': {'@context': 'http://iiif.io/api/annex/openannotation/context.json', 'type': 'iiif:ImageApiSelector', 'rotation': '90'}} is not of type 'array'">]
Message: Error 6 of 6.
 Message: '/recipe/0040-image-rotation-service/canvas/p1#xywh=155,-148,1642,2556' is not valid under any of the given schemas
 **
 Json_path: $.items[0].items[0].items[0].target
 Instance: /recipe/0040-image-rotation-service/canvas/p1#xywh=155,-148,1642,2556
 Context: [<ValidationError: "'/recipe/0040-image-rotation-service/canvas/p1#xywh=155,-148,1642,2556' is not valid under any of the given schemas">, <ValidationError: "'/recipe/0040-image-rotation-service/canvas/p1#xywh=155,-148,1642,2556' is not of type 'array'">]
```

**Comment by triplingual** [comment]
Just re-pulled the validator to see if that was the problem, but it still failed.

**Comment by triplingual** [comment]
The validation is with the local validator. I'm getting weird errors in general locally with validation. I may need to clone afresh and see what happens.

**Comment by glenrobson** [comment]
Changes now in Trip's branch so closing.

**Pull request closed without merging**
