### PR TITLE
Recipe #0053—Related Machine-Readable Resources with seeAlso

### PR DESCRIPTION
**Pull request by triplingual**
This PR addresses issue #53, introducing the way to point to related machine-readable resources such as Dublin Core, MODS, JSON, or RDF. These resources are not representations of the resource containing the `seeAlso` property.

### CODE REVIEW

**Comment by triplingual** [comment]
[Deployment main page](https://preview.iiif.io/cookbook/0053-seeAlso/index.html)
[Direct link to recipe](https://preview.iiif.io/cookbook/0053-seeAlso/recipe/0053-seeAlso/)

**Comment by glenrobson** [comment]
I think the only change requested from TRC was the linking of the seeAlso parameter here:

https://github.com/IIIF/trc/issues/63#issuecomment-781550512

once that is done I think we can merge this.

**Comment by triplingual** [comment]
> I think the only change requested from TRC was the linking of the seeAlso parameter here:
> 
> [IIIF/trc#63 (comment)](https://github.com/IIIF/trc/issues/63#issuecomment-781550512)
> 
> once that is done I think we can merge this.

Done with https://github.com/IIIF/cookbook-recipes/pull/218/commits/3656c066b1c603097b74e0d9bba8d30550b6fefb

**Comment by glenrobson** [comment]
Great thanks Trip! Merged

**Pull request merged**
