### PR TITLE
Recipe #0004 — Image different size to canvas

### PR DESCRIPTION
**Pull request by triplingual**
Recipe #4 never went through the proper review process. This PR will remedy that.

### CODE REVIEW

**Comment by triplingual** [comment]
Preview main page: https://preview.iiif.io/cookbook/0004-canvas-size/
Direct link to recipe: https://preview.iiif.io/cookbook/0004-canvas-size/recipe/0004-canvas-size/

**Comment by glenrobson** [comment]
The cookbook editors asked for the following changes but once done are happy for it to go to the TRC without a second review:

* In Restrictions
 * Could you add a point to say the Aspect ratio should be consistent between the source image and the canvas otherwise you would get unpredictable stretching and distorting. 

In Related:
 * Could you remove Multi Image Multi Choice  
 * Could you add a Link to a A/V recipe which covers behaviours as this should cover the stretch / cut functionality when the canvas is a different size to the audio/file file.

**Comment by triplingual** [comment]
(Munging into a to-do list)

- [ ] In "Restrictions" section: Note that the aspect ratio should be consistent between the source image and the canvas; otherwise you would get unpredictable stretching and distorting.
- [ ] In "Related Recipes" section: Remove "Multi Image Multi Choice"
- [ ] In "Related Recipes" section: Add link to A/V recipe covering `behavior` (to address the stretch / cut functionality when the canvas is a different size to the audio/video file)

**Comment by triplingual** [comment]
Had to make the addition in Related Recipes a hypothetical, but changes made.

**Comment by glenrobson** [comment]
Thanks Trip, changes look great.

**Comment by glenrobson** [comment]
A small typo picked up by @regisrob and then I think this is good to be merged:

"Small typo in the Restrictions paragraph (?):
consistend => consistent (I suppose)"

**Comment by triplingual** [comment]
> A small typo picked up by @regisrob and then I think this is good to be merged:
> 
> "Small typo in the Restrictions paragraph (?):
> consistend => consistent (I suppose)"

Fixed with https://github.com/IIIF/cookbook-recipes/pull/178/commits/8858e2c535fddd8931738cf4e33b768ee8e9aa22

**Comment by glenrobson** [comment]
Great thanks.

**Pull request merged**
