### PR TITLE
Recipe #0007 — Embedding HTML

### PR DESCRIPTION
**Pull request by triplingual**
This is my first PR for a recipe. Hope it's something approaching discussable. 😀

### CODE REVIEW

**Comment by glenrobson** [comment]
(Automated comment): Branch aviliable for testing at https://preview.iiif.io/cookbook/0007-embedding-html

**Comment by glenrobson** [comment]
Direct link to recipe: https://preview.iiif.io/cookbook/0007-embedding-html/recipe/0007-string-formats/

**Comment by triplingual** [comment]
Changes from #cookbook call last Friday
+ Change highlighted line number
+ Change to use https://fixtures.iiif.io/info.html?file=/images/Glen/photos/gottingen.jpg because single image
+ Add text saying markup is not allowed in `label` or other props
+ Add example of HTML in `metadata` and `requiredStatement`
    + Cf  https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100051917418.0x000001/manifest.json
+ Also author in `metadata` with link to the author’s site/page
    + For markup in attribution see https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022545251.0x000002/manifest.json
+ Motivation should be `painting`
+ Canvas dimensions should match contained image dimensions

**Comment by triplingual** [comment]
Non-validation of CC BY-SA 3.0 is known validator bug. @glenrobson will address.

**Comment by triplingual** [comment]
Added this link per cookbook call 9 Apr 2020.

**Comment by glenrobson** [comment]
Hi Trip, the cookbook editors reviewed your recipe and were happy to approve it to go to the TRC with the following changes incorporated: 

 * Could you move the “For security reasons” paragraph into Restrictions? 
 * Can you implement the new Viewer and Json viewer imports? This will resolve an issue we noticed with the `JSON-LD` and `View in UV` were on different lines and also you were using a different UV version to another recipe. 

Once these two changes have been done I will mark it as ready to go to TRC.

Thanks

**Comment by triplingual** [comment]
Merged master branch, implemented Cookbook Editor review requests

**Comment by glenrobson** [comment]
(Automated comment): Branch available for testing at https://preview.iiif.io/cookbook/0007-embedding-html

**Pull request merged**
