### PR TITLE
Recipe #0032: Simplest Collection

### PR DESCRIPTION
**Pull request by mathewjordan**
This PR addresses https://github.com/IIIF/cookbook-recipes/issues/32, creating a recipe for the simplest possible Collection.

### CODE REVIEW

**Comment by glenrobson** [comment]
Review by the Cookbook editors:

Use case
 * Could you reword the use case to give a user respective and more direct to why you want to do use a collection and also keep it simple. Could include links to other recipes for more complex use cases. 
 
Implementation notes
 * Mention collection behaviours: https://iiif.io/api/presentation/3.0/#behavior multi-part (and link to [Multi Volume](https://preview.iiif.io/cookbook/0032-collection/recipe/0030-multi-volume/) and together. 

Example
 * Could you use the Image service in the Manifests?

Restrictions
 * Add restriction that a collection structure is not for table of contents like interface although this maybe how the UV does it other viewers do it differently. For a table of contents example see: [Multiple Volumes in a Single Bound Volume](https://preview.iiif.io/cookbook/0032-collection/recipe/0031-bound-multivolume/)

Related recipes: 
 * Remove [Book with Table of Contents](https://preview.iiif.io/cookbook/0032-collection/recipe/0024-book-4-toc/), 
  * Add Newspaper recipe 

The editors would like to see the new version before it goes to the TRC.

**Comment by mathewjordan** [comment]
@glenrobson @triplingual The updates in the Example section have been completed. The Clover bug noted earlier has been addressed as well. I did not that I could not figure out how Collections work in Annona. Unless I'm completely missing something, I don't know if it should be included as a supporting viewer. Best.

**Comment by triplingual** [comment]
Annona works IIRC, but it's not the most obvious feature of it. ([Short screencast for showing the Annona UI w/r/t collections](https://yaleedu-my.sharepoint.com/:v:/g/personal/trip_kirkpatrick_yale_edu/EU40LQGsJZ5Cv7CSkmXolUQBVPrywgqgc6zZAhiefFjJHw?e=q8swQQ))

**Comment by glenrobson** [comment]
Hi Matt,

Sorry for not sending these comments out earlier but the editors are happy for this to go through. They asked if you could add Annona support for the collections. They also asked me to pass on that they believe the edits you've done since the last version have greatly improved the readability of the recipe.

 Are you able to make the TRC call next Wednesday (15th of November) at 12:00pm ET? I will be sending out the issues and agenda on Monday.

Thanks for your work on this.

Glen

**Comment by mathewjordan** [comment]
> Hi Matt,
> 
> Sorry for not sending these comments out earlier but the editors are happy for this to go through. They asked if you could add Annona support for the collections. They also asked me to pass on that they believe the edits you've done since the last version have greatly improved the readability of the recipe.
> 
> Are you able to make the TRC call next Wednesday (15th of November) at 12:00pm ET? I will be sending out the issues and agenda on Monday.
> 
> Thanks for your work on this.
> 
> Glen

@glenrobson I made the update to add Annona to the list of supporting viewers. And yes, I'll be there for TRC on Wednesday! -Best

**Comment by mathewjordan** [comment]
> Annona works IIRC, but it's not the most obvious feature of it. ([Short screencast for showing the Annona UI w/r/t collections](https://yaleedu-my.sharepoint.com/:v:/g/personal/trip_kirkpatrick_yale_edu/EU40LQGsJZ5Cv7CSkmXolUQBVPrywgqgc6zZAhiefFjJHw?e=q8swQQ))

Thank you @triplingual. I somehow missed that.

**Comment by mathewjordan** [comment]
@glenrobson I believe I have made the change (link for `behavior`) required to publish this.

**Comment by glenrobson** [comment]
Thanks Mat, looks great. Cheers Glen

**Pull request merged**
