### PR TITLE
0006 internationalization and multi-language values

### PR DESCRIPTION
**Pull request by kirschbombe**
Issue: https://github.com/IIIF/cookbook-recipes/issues/6
Preview: https://preview.iiif.io/cookbook/0006-multilingual/recipe/0006-text-language/

### CODE REVIEW

**Comment by glenrobson** [comment]
Comments from the Cookbook editors:

### Implementation notes
 * Could you move the last two paragraphs to the front as they seem very important messages for the reader. 
 * Could you re-write the dot notation message to:

"It should be noted that BCP 47 allows hyphen breaks for locale and scripts (e.g. en-US) and if you are processing these manifests with Javascript it will break the . notation features for navigating JSON object so you should use brackets for accessing language properties."

### Example
Could you change: “The image was sourced via Wikimedia Commons and is public domain.” to “The image in this example was sourced via Wikimedia Commons and is public domain.”

### Related recipes

Could you remove the existing ones as they don't seem awfully relevant and add a link to the rights and metadata recipes? 

Other than the above the editors were happy for this to go to TRC without another review.

**Comment by kirschbombe** [comment]
Thanks, @glenrobson. I made the requested changes, but had to rework the Implementation notes section a bit since just moving the two paragraphs to the top affected the flow. Can you review the edits to make sure they look OK and achieve the desired result?

**Comment by glenrobson** [comment]
It looks great Dawn. Thanks

**Comment by glenrobson** [comment]
This has been approved by the TRC but they have requested the following changes:

* Remove the none case from the label in example lines 12-14 
* It would be useful to have an example of a metadata element with both labels and values in multiple languages (French and English as per the current examples)

**Comment by kirschbombe** [comment]
@glenrobson - I removed the `none` case from the manifest label and I updated the `summary` property with both English and French. I also changed the field in the `metadata` property to "Subject" and included subject values in both English and French. This should take care of the fixes, but let me know if it still needs work.

**Comment by glenrobson** [comment]
Sorry Dawn would it be possible to include the subject example in addition to the author one? I think its useful to show both and I believe the intention of the comment from TRC was in addition rather than replacing.

**Comment by kirschbombe** [comment]
@glenrobson I can add the author back in, but I can't really make that one both French and English which is why I switched it to Subject. It will still use "none" for the value language map -- will that be OK?

**Comment by glenrobson** [comment]
Thanks Dawn thats perfect. I think its important to show what I think will be a common use case that you have translated labels but not content.

**Pull request merged**
