### PR TITLE
Recipe #0299 Addressing a Region

### PR DESCRIPTION
**Pull request by triplingual**
This PR addresses #299, for putting a region of a IIIF resource on a Canvas by itself

### CODE REVIEW

**Comment by glenrobson** [comment]
The editors had a look at this recipe and I'm afraid found it quite difficult to parse the implementation notes and wondered if it could be simplified to give less options and focus on the recipe its self. 

Specifically they came up with the following suggestions:

 * Turn on validation: https://github.com/IIIF/cookbook-recipes/blob/c7e929292b2c1fcadbcefa00fa15391b5d5ae39a/.github/workflows/preview.yml#L73 although this has now been fixed in master so you can just update. 
 * First paragraph proposes many options and its unclear on which one we are going for. Could we focus on the details of the recipe and then in the final two paragraphs of implementation notes mention the other two options? Options include:
    -  Second option use a straight IIIF Image link like in recipe 001
    - Third option using something like content state (I'm not sure this is mentioned)
    - Forth option use an annotation like tagging recipe 

 * Suggestions for the following paragraphs:
 
“Note, however (as discussed in[ recipe 4](https://preview.iiif.io/cookbook/0299-region/recipe/0004-canvas-size/)) that the Canvas is a dimensionless set of coordinates. If desired, the dimensions of the Canvas may be different numeric values than the region you are displaying, but must be the same proportions if you want the region displayed with an unchanged dimension ratio.” 

  * Can we simplify? Something like the canvas dimensions will match the region of the sub image if you want the sub image to fill the entire canvas. (I think mentioning the dimensionless ness of the canvas will just confuse)
   
“When transmitting coordinates and dimensions for the region, note that the region property of the selector takes only those values, comma-separated, rather than the values in addition to a parameter type as the FragmentSelector uses” 

   * Note the region parameter of the image selector matches the parameters to the image API https://iiif.io/api/image/3.0/#41-region for example `x,y,width,height` or `pct:x,y,w,h`
  
“In addition, when using an Image service to retrieve your intended region of a IIIF resource, the Annotation body containing the resource is constructed as a[ SpecificResource](https://www.w3.org/TR/annotation-model/#specific-resources) containing in turn a source with the resource’s details.”

   * In this recipe the canvas resource (source IIIF Image) has the dimensions of the full sized image but then the region is pulled out by using a selector of type ImageAPISelector to retrieve the region from the source image. 

I'm afraid as there are quite a few suggestions the editors would like to see it again before it goes to TRC.

**Comment by triplingual** [comment]
Totally fine to have a try at the cx and get it to them again. Comprehensibility is a fairly low bar for recipes. 🙂

**Comment by triplingual** [comment]
Validation addressed with 5dcf26b

**Comment by glenrobson** [comment]
Cookbook editors are happy for this to go through with the following notes. They appreciated the work you have done and found it much clearer to read. 

 * Maybe one to discuss in the cookbook meeting tomorrow but the editors were wondering whether we should add a new heading for ‘Alternatives’ or `Other solutions` to group the alternative solutions. This may not be necessary for early recipes but now they are getting more complicated it may help to only have the solution to the recipe in implementation notes and call out alternatives in its own section. 
 * The editors didn't think Annona worked with this recipe.  
 * In the restriction section could you link to this recipe when talking about timecodes in target as one example: https://preview.iiif.io/cookbook/0299-region/recipe/0064-opera-one-canvas/

**Comment by glenrobson** [comment]
Brian makes a good point that this isn't in the context but I think in the rotation recipe we decided to go ahead as the editors are looking at updating the version 3 context. 

Glen will flag this with the Editors as we now have 2 recipes that use ImageAPISelector and soon will be 3.

**Pull request merged**
