### PR TITLE
Recipe #0318: Using navPlace and navDate Together

### PR DESCRIPTION
**Pull request by mikeapp**
Preview: https://preview.iiif.io/cookbook/0318/recipe/0318-navPlace-navDate/

### CODE REVIEW

**Comment by glenrobson** [comment]
The cookbook editors had the following comments on the recipe:

 * Could you rename the title to: "Locating an item in place and time"  
 * Remove second paragraph from use case as this is viewer specific rather than recipe specific. 
 * Remove: [Represent Canvas Fragment as a Geographic Area in a Web Mapping Client](https://preview.iiif.io/cookbook/0318/recipe/0139-geolocate-canvas-fragment/) from related recipe
 * Can we move the link to the collection and manifest links above the full example like this one for table of contents: https://preview.iiif.io/cookbook/0318/recipe/0024-book-4-toc/
 
 So it would look something like this:
 
 [NavPlace and NavDate Collection](https://preview.iiif.io/cookbook/0318/recipe/0318-navPlace-navDate/collection.json)
  * [Castel Sant'Angelo, Rome](https://preview.iiif.io/cookbook/0318/recipe/0318-navPlace-navDate/manifest-1.json)
  * [The Colosseum](https://preview.iiif.io/cookbook/0318/recipe/0318-navPlace-navDate/manifest-2.json)
  * [The Arch of Titus from the Forum, Rome, ca. 1725](https://preview.iiif.io/cookbook/0318/recipe/0318-navPlace-navDate/manifest-3.json)
 * [The Temple of Vesta, Rome, 1849](https://preview.iiif.io/cookbook/0318/recipe/0318-navPlace-navDate/manifest-4.json)
 * [A View of Trajan’s Forum, Rome, 1821](https://preview.iiif.io/cookbook/0318/recipe/0318-navPlace-navDate/manifest-5.json)
 
 [JSON-LD](https://preview.iiif.io/cookbook/0318/recipe/0318-navPlace-navDate/manifest-1.json)
 << example >>
 
 The cookbook editors would like a quick look at the changes before it goes to the TRC but are happy for it to go to the May TRC.
 
 Thanks

**Comment by triplingual** [comment]
(The sub-message on immediately preceding commit should have touched @mikeapp instead. Apologies.)

**Comment by glenrobson** [comment]
Add navPlace viewer and then ready to merge.

**Comment by glenrobson** [comment]
We should change the collection so that it also has the navDates and navPlaces to allow efficient client processing. 

Show collection in the example and links to viewers.

**Pull request merged**
