### PR TITLE
Recipe #0434 Choice with Audio or Video

### PR DESCRIPTION
**Pull request by triplingual**
This PR addresses #434, for presenting a choice of audio or video files/formats to a 
viewer and reader.

### CODE REVIEW

**Comment by triplingual** [comment]
A short note about the additional metadata and related institutional metadata in this recipe:
The sound used in the recipe originated in Nigeria's Kwara State, and was recorded by the University of Ibadan's Institute of African Studies. UCLA Library acts in a custodial capacity to present the files on the web for global listeners. With the fraught intellectual and political relationships between European/American and African higher educational institutions as well as between institutions of higher education and folk musicians, it seemed important to me to make clear some of the who, what, when, and where of the sound.

**Comment by glenrobson** [comment]
Note I think we are missing the line highlighting.

**Comment by glenrobson** [comment]
Typo in label of manifest: Exceprt from Egbe Iyawo

**Comment by triplingual** [comment]
- [ ] Suggest moving the attribution and other info to the text of the recipe not in the manifest if possible.
- [ ] The canonical URI should be http://creativecommons.org/publicdomain/zero/1.0/. It is what is dereferenceable with content negotiation and with the API:[ https://api.creativecommons.org/rest/1.5/details?license-uri=http://creativecommons.org/publicdomain/zero/1.0/](https://api.creativecommons.org/rest/1.5/details?license-uri=http://creativecommons.org/publicdomain/zero/1.0/)
- [ ] Add simple audio to related as it shows the difference between a single resource rather than others
- [ ] @glenrobson to check validation
- [ ] Not related recipes as they are build on recipes:
  - [ ] Begin playback at a specific point - Time-based media for specifying a playback start point
  - [ ] Audio Presentation with Accompanying Image for considering adding an image to the interface
- [ ] Add simple audio
- [ ] Restrictions: remove , but not all viewers will recognize Choice. As this will age and most of the viewers do seem to support the choice.

**Pull request merged**
