### PR TITLE
0015 - Start (start playback at a particular point)

### PR DESCRIPTION
**Pull request by tomcrane**
Still a WIP, just a couple of tweaks.

### CODE REVIEW

**Comment by glenrobson** [comment]
(Automated comment): Branch aviliable for testing at https://preview.iiif.io/cookbook/0015-start

**Comment by glenrobson** [comment]
(Automated comment): Branch available for testing at https://preview.iiif.io/cookbook/0015-start

**Comment by kirschbombe** [comment]
For your review :) ...and I have a few questions:
- Is there a list of tags to choose from? I have audio and video in there now, but can remove audio since it's a video. Is there another tag I should include?
- The `start` feature isn't working when playing in UV - is this bc it hasn't been implemented yet or is it something in the manifest? If not implemented, I assume I should remove the UV link?

Looking forward to suggestions.

**Comment by glenrobson** [comment]
Specific Recipe link: https://preview.iiif.io/cookbook/0015-start/recipe/0015-start/

**Comment by glenrobson** [comment]
Hi Dawn,

Just looking through the recipe and noted the following:

 * You mention the 3 selectors defined in the IIIF specification but there are also the ones defined by the Web Annotations standard (https://www.w3.org/TR/annotation-model/#selectors) which can be used and in particular I've seen the FragmentSelector used a lot. 
 * with the links to the Spec (annex and 3.0) could you use https://iiif.io rather than the preview URLs 
 * I'm afraid I also don't understand the "PointSelector cannot be used on a w,h Canvas. " comment.

Otherwise it looks good to me.

**Comment by glenrobson** [comment]
Related Issue: [#15 - Start](https://github.com/IIIF/cookbook-recipes/issues/15)

**Comment by glenrobson** [comment]
Comments from the cookbook editors:

 * OK to include link to highlight UV doesn’t work. For TRC Glen should include link to UV issue in the TRC ticket.  
 * In related recipes add:
    * Add link to simple audio recipe 
    * Add link to Start with image content. 
 * There was some discussion on the "About selector classes" part of the recipe. Although it is useful to detail the different selectors available, the cookbook editors thought it would be better to focus on the selectors that would work with the `start` property and in this case it was thought the PointSelector was the only one that was applicable for AV.

As there is potentially some work involved in the selector section the cookbook editors didn't think it was ready to send to the TRC tomorrow.

**Comment by kirschbombe** [comment]
Thanks, @glenrobson! I'll have this ready for review by our group before our meeting next Friday.

**Comment by kirschbombe** [comment]
I've updated the Selector class section and added a link to the simple audio recipe. There is no issue or recipe for Start with image content yet, so I included a placeholder (commented out). I can create new issues for Start for image and for spatial if needed. I'll bring this up at the next cookbook meeting if time.

**Comment by glenrobson** [comment]
Create issues for start with image and audio and then create link like:

https://raw.githubusercontent.com/IIIF/cookbook-recipes/d1999a74e8a3de2ff76d86fcb7af1aeed264a461/recipe/0008-rights/index.md

**Comment by glenrobson** [comment]
The Cookbook editors have approved this recipe with no changes :-).

**Comment by glenrobson** [comment]
Approved by TRC with no changes so merging.

**Pull request merged**
