### PR TITLE
Recipe #0117—Add Image Thumbnails

### PR DESCRIPTION
**Pull request by triplingual**
This PR addresses issue #117 (in turn connected to #12), introducing the use of thumbnails for representing content views.

### CODE REVIEW

**Comment by triplingual** [comment]
[Index preview](https://preview.iiif.io/cookbook/0117-add-image-thumbnail/)
[Recipe preview](https://preview.iiif.io/cookbook/0117-add-image-thumbnail/recipe/0117-add-image-thumbnail/)

**Comment by glenrobson** [comment]
Comments from Cookbook editor meeting:

### In Use case section
 * Could you make the Spotlight link work? 
 * Can you move “However, in this particular case, your booklet’s Manifest begins with a color calibration image at the start and so you benefit from declaring the second image as the thumbnail.” down to the Example section (but see comments on Manifest layout below). 

### In Example section
 * The last sentence ends in “To see…”. We wondered if you were going to on to explain how to view the manifest thumbnail in Mirador?
 * As the UV doesn't use the Manifest thumbnail we suggested removing it from the list of viewers.

### In Manifest
 * Could you change the http link in body:id on line 24 to https? 
 * Can you remove the canvas level thumbnail. 
 * To simplify the manifest can you remove second canvas but use this image as the thumbnail?
 * Note the above change will require rewording the example description. 

### In Related
 * Remove: Viewing direction and its effect on navigation
 * Replace simple image with Support Deep Viewing with Basic Use of a IIIF Image Service

The editors are happy to approve with the above changes but would like a quick look at the example part before sending to TRC.

**Comment by triplingual** [comment]
I've got no principled problem with any of these, but a couple responses.

+ The brackets around [Spotlight] were more to consider whether we want to name a specific discovery interface or rather to phrase it more like ". . . such as Mirador or Universal Viewer to common discovery services and other aggregators to homegrown solutions."
+ The "To see" is more or less legacy text leftover from the previous version of the Example section, which pointed readers to #10 for the ability to see what UV does when you don't specify thumbs. If I'm removing UV from this recipe, it's moot and I'll strike "To see" as well.

Sorry this one was sloppier than most of my others. Should be able to get to these tomorrow (21 October).

**Comment by glenrobson** [comment]
I think its fine to leave spotlight in as an example. In the cookbook meeting no one objected to naming a specific tool only to the fact it looked like a link that wasn't clickable.

**Comment by triplingual** [comment]
_Could you make the Spotlight link work?_
✅ Changed to plain text

_Can you move “However, in this particular case, your booklet’s Manifest begins with a color calibration image at the start and so you benefit from declaring the second image as the thumbnail.” down to the Example section (but see comments on Manifest layout below)._
✅ (Chunking change confirmations and developinging locally, so I'll confirm this here and make further adjustment in a moment)

**Comment by triplingual** [comment]
_The last sentence ends in “To see…”. We wondered if you were going to on to explain how to view the manifest thumbnail in Mirador?_
✅ Stripped this text

_As the UV doesn't use the Manifest thumbnail we suggested removing it from the list of viewers._
✅ Removed

**Comment by triplingual** [comment]
_Could you change the http link in body:id on line 24 to https?_
✅ Changed

_Can you remove the canvas level thumbnail._
✅ Removed

_To simplify the manifest can you remove second canvas but use this image as the thumbnail?_
✅ Removed

_Note the above change will require rewording the example description._
✅ Done. Do check the example text, as I felt it needed significant editing after incorporating these changes.

**Comment by triplingual** [comment]
_Remove: Viewing direction and its effect on navigation_
✅ Removed

_Replace simple image with Support Deep Viewing with Basic Use of a IIIF Image Service_
✅ Replaced

**Comment by triplingual** [comment]
All changes made, I believe.

**Comment by glenrobson** [comment]
Hi Trip, 

Thanks for making those changes and I passed it to the editors to have a quick look and they mentioned:

* Could you link Spotlight (https://github.com/projectblacklight/spotlight unless you know of a better link) as it won't be clear for those that haven't heard of it what it is.
 * Also in the example section could you add an explanation of when Mirador would use the Manifest thumbnail?  I think its only when you view the list of manifests. 

Thanks

Glen

**Comment by triplingual** [comment]
Made the changes. Light edit to the (newly) penultimate sentence of the Example text because I didn't like it in the new context.

The other possible good link for Spotlight would be the project brochureware page rather than the code repo: http://spotlight.projectblacklight.org/

**Comment by glenrobson** [comment]
Issue passed in TRC with no changes requested so I am merging.

**Pull request merged**
