### PR TITLE
Recipe #0258 Tagging Annotation with External Resource

### PR DESCRIPTION
**Pull request by triplingual**
This PR addresses #258, for creating a tagging annotation that refers to an external resource

### CODE REVIEW

**Comment by glenrobson** [comment]
The cookbook editors are happy for this to go to the TRC next week but asked for the following changes:

 * Could you add code highlighting to the Manifest for the tagging annotation
 * Remove “Because each body is used for tagging, we have put that as the value of the motivation property on the Annotation rather than making use of the Specific Resource’s purpose property.” from the example description as we don’t think there is any mention of purpose else where and this confuses the recipe a bit. We don't think there is a need to mention purpose in this recipe as its not used.  
 * Could you add an explanation for the second body i.e. we want to add a label for the URI in the first body. Maybe in the implementation notes or example. It would be valid to have a single body with the URI but to make it easier for a viewer/client we have included a second body as a label.
 * Below the Manifest could you take out the text “The direct link to the fixture is a useful convenience.”

**Comment by triplingual** [comment]
- [ ] Could you add code highlighting to the Manifest for the tagging annotation
- [ ] Remove “Because each body is used for tagging, we have put that as the value of the motivation property on the Annotation rather than making use of the Specific Resource’s purpose property.” from the example description as we don’t think there is any mention of purpose else where and this confuses the recipe a bit. We don't think there is a need to mention purpose in this recipe as its not used.
- [ ] Could you add an explanation for the second body i.e. we want to add a label for the URI in the first body. Maybe in the implementation notes or example. It would be valid to have a single body with the URI but to make it easier for a viewer/client we have included a second body as a label.
  - To address this one, I did a little editing instead. I already had
  > In addition to tagging the fountain with text giving its name, we are adding for this recipe an additional Annotation `body` that points to the Wikidata entry for the fountain.
  - and changed it to 
  > While the Annodation `body` that points to the Wikidata entry for the fountain is valid all alone, we've added an additional `body` to provide the viewer a natural language textual label to display to a person using that viewer.
  - It's not thrilling prose, but does it get at the thinking behind the comments?
- [ ] Below the Manifest could you take out the text “The direct link to the fixture is a useful convenience.”
  - 🥴

**Comment by triplingual** [comment]
Connections:
08b0c51: https://github.com/IIIF/trc/issues/85#issuecomment-988988362, https://github.com/IIIF/trc/issues/85#issuecomment-987134174
10b4a68: https://github.com/IIIF/trc/issues/85#issuecomment-989006553
3b9af42: https://github.com/IIIF/trc/issues/85#issuecomment-987134174
537217b: https://github.com/IIIF/trc/issues/85#issuecomment-988985391

**Comment by glenrobson** [comment]
Thanks @triplingual merging now.

For info when I merged the latest from master I had to add the `viewer` and `topic` front matter to get it to pass validation.

**Pull request merged**
