### PR TITLE
Update recipe 2

### PR DESCRIPTION
**Pull request by azaroth42**
Mostly in the example, some tweaks to the recipe content.

### CODE REVIEW

**Comment by glenrobson** [comment]
(Automated comment): Branch aviliable for testing at https://preview.iiif.io/cookbook/0002-simplest-audio-update

**Comment by zimeon** [comment]
Specific page on preview: https://preview.iiif.io/cookbook/0002-simplest-audio-update/recipe/0002-mvm-audio/

**Comment by glenrobson** [comment]
I've updated the Ids so they use the new Jekyll variables and also linked to a real audio file hosted in the iiif s3 bucket. 

Does this need to go through TRC or can it be approved as its one of the initial cases?

**Comment by tomcrane** [comment]
This example was essentially published as an example to get the cookbook started. I don't think it needs to go to TRC, but don't object if it does.

**Comment by tomcrane** [comment]
I also think it should be merged - it's already in `master`, this PR does not change the text of the recipe - it provides some essential fixes.

**Comment by tomcrane** [comment]
I made one further tweak in the above commit.

**Comment by glenrobson** [comment]
(Automated comment): Branch available for testing at https://preview.iiif.io/cookbook/0002-simplest-audio-update

**Comment by glenrobson** [comment]
Added a link to the UV but get the following error when opening:

"Unable to determine media type"

**Comment by glenrobson** [comment]
Looks like the audio support is an issue with the UV rather than the recipe: https://github.com/UniversalViewer/universalviewer/issues/730

Merging this as discussed in the editors channel as existing live recipe doesn't point to a working audio file.

**Pull request merged**
